/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author finkl
 */
public class CalculadoraSimples extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraSimples
     */
    public CalculadoraSimples() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        textoValor1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botaoDiv = new javax.swing.JButton();
        botaoAdi = new javax.swing.JButton();
        botaoSub = new javax.swing.JButton();
        botaoMul = new javax.swing.JButton();
        textoValor2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        textoResultado = new javax.swing.JTextField();
        textoCalculo = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("\ttext área");
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora Simples");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(35, 37, 45));
        setPreferredSize(new java.awt.Dimension(380, 650));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(43, 45, 55));

        textoValor1.setBackground(new java.awt.Color(35, 37, 45));
        textoValor1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        textoValor1.setForeground(new java.awt.Color(255, 255, 255));
        textoValor1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        textoValor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoValor1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VALOR 1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("VALOR 2");

        botaoDiv.setBackground(new java.awt.Color(35, 37, 45));
        botaoDiv.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        botaoDiv.setForeground(new java.awt.Color(122, 191, 176));
        botaoDiv.setIcon(new javax.swing.ImageIcon("C:\\Users\\finkl\\Documents\\NetBeansProjects\\InterfaceGrafica\\src\\main\\java\\imagens\\div.png")); // NOI18N
        botaoDiv.setBorder(null);
        botaoDiv.setPreferredSize(new java.awt.Dimension(80, 80));
        botaoDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDivActionPerformed(evt);
            }
        });

        botaoAdi.setBackground(new java.awt.Color(35, 37, 45));
        botaoAdi.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        botaoAdi.setForeground(new java.awt.Color(122, 191, 176));
        botaoAdi.setIcon(new javax.swing.ImageIcon("C:\\Users\\finkl\\Documents\\NetBeansProjects\\InterfaceGrafica\\src\\main\\java\\imagens\\addi.png")); // NOI18N
        botaoAdi.setBorder(null);
        botaoAdi.setPreferredSize(new java.awt.Dimension(80, 80));
        botaoAdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdiActionPerformed(evt);
            }
        });

        botaoSub.setBackground(new java.awt.Color(35, 37, 45));
        botaoSub.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        botaoSub.setForeground(new java.awt.Color(122, 191, 176));
        botaoSub.setIcon(new javax.swing.ImageIcon("C:\\Users\\finkl\\Documents\\NetBeansProjects\\InterfaceGrafica\\src\\main\\java\\imagens\\sub.png")); // NOI18N
        botaoSub.setBorder(null);
        botaoSub.setPreferredSize(new java.awt.Dimension(80, 80));
        botaoSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSubActionPerformed(evt);
            }
        });

        botaoMul.setBackground(new java.awt.Color(35, 37, 45));
        botaoMul.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        botaoMul.setForeground(new java.awt.Color(122, 191, 176));
        botaoMul.setIcon(new javax.swing.ImageIcon("C:\\Users\\finkl\\Documents\\NetBeansProjects\\InterfaceGrafica\\src\\main\\java\\imagens\\mult.png")); // NOI18N
        botaoMul.setBorder(null);
        botaoMul.setPreferredSize(new java.awt.Dimension(80, 80));
        botaoMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMulActionPerformed(evt);
            }
        });

        textoValor2.setBackground(new java.awt.Color(35, 37, 45));
        textoValor2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        textoValor2.setForeground(new java.awt.Color(255, 255, 255));
        textoValor2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jButton2.setBackground(new java.awt.Color(35, 37, 45));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("LIMPAR");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botaoAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botaoSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botaoDiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botaoMul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(textoValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(textoValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoMul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoDiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 370, 410));

        jPanel2.setBackground(new java.awt.Color(35, 37, 45));

        titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("CALCULADORA");

        textoResultado.setBackground(new java.awt.Color(35, 37, 45));
        textoResultado.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        textoResultado.setForeground(new java.awt.Color(255, 255, 255));
        textoResultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textoResultado.setBorder(null);

        textoCalculo.setBackground(new java.awt.Color(35, 37, 45));
        textoCalculo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textoCalculo.setForeground(new java.awt.Color(255, 255, 255));
        textoCalculo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textoCalculo.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textoCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(textoCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 240));

        setSize(new java.awt.Dimension(380, 650));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textoValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoValor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoValor1ActionPerformed

    private void botaoDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDivActionPerformed
        float resultado = Float.parseFloat(textoValor1.getText()) / Float.parseFloat(textoValor2.getText());
        textoCalculo.setText(textoValor1.getText() + " / " + textoValor2.getText());
        textoResultado.setText(String.valueOf(resultado));
    }//GEN-LAST:event_botaoDivActionPerformed

    private void botaoMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMulActionPerformed
        float resultado = Float.parseFloat(textoValor1.getText()) * Float.parseFloat(textoValor2.getText());
        textoCalculo.setText(textoValor1.getText() + " x " + textoValor2.getText());
        textoResultado.setText(String.valueOf(resultado));
    }//GEN-LAST:event_botaoMulActionPerformed

    private void botaoSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSubActionPerformed
        float resultado = Float.parseFloat(textoValor1.getText()) - Float.parseFloat(textoValor2.getText());
        textoCalculo.setText(textoValor1.getText() + " - " + textoValor2.getText());
        textoResultado.setText(String.valueOf(resultado));
    }//GEN-LAST:event_botaoSubActionPerformed

    private void botaoAdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdiActionPerformed
        float resultado = Float.parseFloat(textoValor1.getText()) + Float.parseFloat(textoValor2.getText());
        textoCalculo.setText(textoValor1.getText() + " + " + textoValor2.getText());
        textoResultado.setText(String.valueOf(resultado));
    }//GEN-LAST:event_botaoAdiActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        textoValor1.setText(String.valueOf(""));
        textoValor2.setText(String.valueOf(""));
        textoCalculo.setText(String.valueOf(""));
        textoResultado.setText(String.valueOf(""));
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraSimples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraSimples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraSimples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraSimples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraSimples().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdi;
    private javax.swing.JButton botaoDiv;
    private javax.swing.JButton botaoMul;
    private javax.swing.JButton botaoSub;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField textoCalculo;
    private javax.swing.JTextField textoResultado;
    private javax.swing.JTextField textoValor1;
    private javax.swing.JTextField textoValor2;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
